name: example-conditional
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world"
        if: github.repository == 'ih-end/Github-Examples'
        run: echo "Hello W"

      - name: "Bye"
        if: github.repository != 'ih-end/Github-Examples'
        run: echo "Bye W"